### ISSUE TITLE
README.md should be updated

### ISSUE THREAD

**Issue by AxelBoldt** [APEXCalculus/APEXCalculusV5#1]
Hello, the file README.md in APEXCalculusV5 still refers to version 4.0 and should probably be updated.

Sorry that I don't have a more substantial contribution to make at this point. Thank you for your work!

**Comment by APEXCalculus** [comment]
Axel!
Thanks. I just updated it. I make the V5 repo straight off the V4 one, and
didn't think about the README until you mentioned it.

Thanks for the support.

Greg

**Comment by rudolf-adamkovic** [comment]
> Thanks. I just updated it.

This issue can be closed then, no?

**Comment by Gomesz785** [comment]
Is this issue solved?

**Comment by AxelBoldt** [comment]
Yes, it's solved.
