### ISSUE TITLE
a=0 in General p-Series

### ISSUE THREAD

**Issue by mszudzik** [APEXCalculus/APEXCalculusV5#12]
https://github.com/APEXCalculus/APEXCalculusV5/blob/2ec7e64191dfabbf1497bc7a00d3e2989614303b/text/08_Series.tex#L168

There is an error in the theorem for the _p_-series test.  In particular, the currently stated theorem is false in the special case when _a_=0.

The current theorem states that

`A general $p$--series $\ds\sum_{n=1}^\infty \frac{1}{(an+b)^p}$ will converge if, and only if, $p>1$.`

The error could be corrected by changing this to

`A general $p$--series $\ds\sum_{n=1}^\infty \frac{1}{(an+b)^p}$ with $a\neq 0$ will converge if, and only if, $p>1$.`

Alternatively, the error could be corrected by changing the definition of a general _p_-series to require that _a_ is nonzero.  (Note that the definition of a general _p_-series is just a few lines before the theorem for the _p_-series test.)

**Comment by APEXCalculus** [comment]
Thanks for the comment. The text has gotten much better over the years with the help of people like you make suggestions and pointing out mistakes.

This error has been caught, though it isn't reflected here. At some point in time this repo has become outdated, with all new work being done in the APEXCalclulusPTX repo. Looking at line 701 & on in https://github.com/APEXCalculus/APEXCalculusPTX/blob/main/ptx/sec_series.ptx, you can see that we've adopted your alternative suggestion of defining the general p-series to have a!=0. Then the theorem holds.

Thanks again for taking the time to submit a comment; sorry it took me a couple of days to respond.
